version: '3.8'

services:
  ms-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ms-db
      - ms-redis
    networks:
      - mapstack-network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  ms-db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mapstack-network

  ms-redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mapstack-network

networks:
  mapstack-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
