version: '3.8'

services:
  ms-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ms-db
      - ms-redis
      - ms-minio
    networks:
      - mapstack-network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  ms-db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mapstack-network

  ms-redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mapstack-network

  ms-minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # APIエンドポイント
      - "9001:9001" # 管理コンソール
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - mapstack-network
    command: server --console-address ":9001" /data

networks:
  mapstack-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  minio-data:
