"""
フロントエンドロードマップのデータを提供するモジュール
"""

# フロントエンドロードマップのノードデータ
frontend_roadmap_nodes = [
    {
        "handle": "internet",
        "node_type": "primary",
        "title": "インターネット",
        "description": "インターネットの仕組み、ブラウザの動作原理、HTTP/HTTPSプロトコルについて学ぶ",
        "position_x": 250,
        "position_y": 0,
    },
    {
        "handle": "html",
        "node_type": "primary",
        "title": "HTML",
        "description": "HTMLの基本構造、セマンティックHTML、フォーム、アクセシビリティについて学ぶ",
        "position_x": 100,
        "position_y": 100,
    },
    {
        "handle": "css",
        "node_type": "primary",
        "title": "CSS",
        "description": "CSSの基本、レイアウト、レスポンシブデザイン、アニメーションについて学ぶ",
        "position_x": 250,
        "position_y": 100,
    },
    {
        "handle": "javascript",
        "node_type": "primary",
        "title": "JavaScript",
        "description": "JavaScriptの基本文法、DOM操作、非同期処理、ES6+の機能について学ぶ",
        "position_x": 400,
        "position_y": 100,
    },
    {
        "handle": "how-internet-works",
        "node_type": "secondary",
        "title": "インターネットの仕組み",
        "description": "ネットワーク、DNS、ホスティング、ブラウザの基本概念",
        "position_x": -60,
        "position_y": -20,
    },
    {
        "handle": "http",
        "node_type": "secondary",
        "title": "HTTP/HTTPS",
        "description": "HTTPメソッド、ステータスコード、ヘッダー、セキュリティ",
        "position_x": 0,
        "position_y": 40,
    },
    {
        "handle": "html-basics",
        "node_type": "secondary",
        "title": "HTML基礎",
        "description": "タグ、要素、属性、構造化",
        "position_x": 0,
        "position_y": 180,
    },
    {
        "handle": "semantic-html",
        "node_type": "secondary",
        "title": "セマンティックHTML",
        "description": "意味のあるHTMLタグの使用方法",
        "position_x": 0,
        "position_y": 250,
    },
    {
        "handle": "forms-validation",
        "node_type": "secondary",
        "title": "フォームとバリデーション",
        "description": "フォーム要素、入力検証、ユーザビリティ",
        "position_x": 0,
        "position_y": 320,
    },
    {
        "handle": "accessibility",
        "node_type": "recommended",
        "title": "アクセシビリティ",
        "description": "WAI-ARIA、キーボードナビゲーション、スクリーンリーダー対応",
        "position_x": 0,
        "position_y": 390,
    },
    {
        "handle": "css-basics",
        "node_type": "secondary",
        "title": "CSS基礎",
        "description": "セレクタ、プロパティ、値、ボックスモデル",
        "position_x": 200,
        "position_y": 180,
    },
    {
        "handle": "layout",
        "node_type": "secondary",
        "title": "レイアウト",
        "description": "フレックスボックス、グリッド、ポジショニング",
        "position_x": 200,
        "position_y": 250,
    },
    {
        "handle": "responsive-design",
        "node_type": "secondary",
        "title": "レスポンシブデザイン",
        "description": "メディアクエリ、ビューポート、モバイルファースト",
        "position_x": 200,
        "position_y": 320,
    },
    {
        "handle": "css-frameworks",
        "node_type": "optional",
        "title": "CSSフレームワーク",
        "description": "Bootstrap、Tailwind CSS、Bulmaなど",
        "position_x": 200,
        "position_y": 390,
    },
    {
        "handle": "js-basics",
        "node_type": "secondary",
        "title": "JavaScript基礎",
        "description": "変数、データ型、関数、スコープ、イベント",
        "position_x": 400,
        "position_y": 180,
    },
    {
        "handle": "dom-manipulation",
        "node_type": "secondary",
        "title": "DOM操作",
        "description": "要素の選択、作成、更新、イベントリスナー",
        "position_x": 400,
        "position_y": 250,
    },
    {
        "handle": "async-js",
        "node_type": "secondary",
        "title": "非同期JavaScript",
        "description": "コールバック、Promise、async/await",
        "position_x": 400,
        "position_y": 320,
    },
    {
        "handle": "es6-plus",
        "node_type": "secondary",
        "title": "ES6+の機能",
        "description": "アロー関数、分割代入、スプレッド構文、クラス",
        "position_x": 400,
        "position_y": 390,
    },
    {
        "handle": "js-frameworks",
        "node_type": "secondary",
        "title": "JavaScriptフレームワーク",
        "description": "モダンなフロントエンド開発に使用される主要なJavaScriptフレームワーク（React、Vue、Angular）について学ぶ",
        "position_x": 125,
        "position_y": 500,
    },
    {
        "handle": "react",
        "node_type": "optional",
        "title": "React",
        "description": "コンポーネント、props、state、hooks、Reduxなど",
        "position_x": 400,
        "position_y": 430,
    },
    {
        "handle": "vue",
        "node_type": "optional",
        "title": "Vue.js",
        "description": "ディレクティブ、コンポーネント、Vuex、Composition API",
        "position_x": 400,
        "position_y": 500,
    },
    {
        "handle": "angular",
        "node_type": "optional",
        "title": "Angular",
        "description": "コンポーネント、サービス、モジュール、RxJS",
        "position_x": 400,
        "position_y": 570,
    },
    {
        "handle": "web-performance",
        "node_type": "recommended",
        "title": "Webパフォーマンス",
        "description": "パフォーマンス最適化、Core Web Vitals、バンドルサイズの削減について学ぶ",
        "position_x": 150,
        "position_y": 620,
    },
    {
        "handle": "performance-metrics",
        "node_type": "secondary",
        "title": "パフォーマンス指標",
        "description": "LCP、FID、CLS、Webパフォーマンスの測定",
        "position_x": 50,
        "position_y": 700,
    },
    {
        "handle": "optimization",
        "node_type": "secondary",
        "title": "最適化テクニック",
        "description": "画像最適化、遅延読み込み、コード分割、キャッシュ",
        "position_x": 250,
        "position_y": 700,
    },
]

# フロントエンドロードマップのエッジデータ
frontend_roadmap_edges = [
    {
        "handle": "internet-to-how-internet-works",
        "source_node_id": "internet",
        "target_node_id": "how-internet-works",
        "edge_type": "animated",
        "source_handle": "left",
        "target_handle": "right",
    },
    {
        "handle": "internet-to-http",
        "source_node_id": "internet",
        "target_node_id": "http",
        "edge_type": "animated",
        "source_handle": "left",
        "target_handle": "right",
    },
    {
        "handle": "html-to-html-basics",
        "source_node_id": "html",
        "target_node_id": "html-basics",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "html-to-semantic-html",
        "source_node_id": "html",
        "target_node_id": "semantic-html",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "html-to-forms-validation",
        "source_node_id": "html",
        "target_node_id": "forms-validation",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "html-to-accessibility",
        "source_node_id": "html",
        "target_node_id": "accessibility",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "css-to-css-basics",
        "source_node_id": "css",
        "target_node_id": "css-basics",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "css-to-layout",
        "source_node_id": "css",
        "target_node_id": "layout",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "css-to-responsive-design",
        "source_node_id": "css",
        "target_node_id": "responsive-design",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "css-to-css-frameworks",
        "source_node_id": "css",
        "target_node_id": "css-frameworks",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "javascript-to-js-basics",
        "source_node_id": "javascript",
        "target_node_id": "js-basics",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "javascript-to-dom-manipulation",
        "source_node_id": "javascript",
        "target_node_id": "dom-manipulation",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "javascript-to-async-js",
        "source_node_id": "javascript",
        "target_node_id": "async-js",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "javascript-to-es6-plus",
        "source_node_id": "javascript",
        "target_node_id": "es6-plus",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "internet-to-html",
        "source_node_id": "internet",
        "target_node_id": "html",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "internet-to-css",
        "source_node_id": "internet",
        "target_node_id": "css",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "internet-to-javascript",
        "source_node_id": "internet",
        "target_node_id": "javascript",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "html-to-js-frameworks",
        "source_node_id": "html",
        "target_node_id": "js-frameworks",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "css-to-js-frameworks",
        "source_node_id": "css",
        "target_node_id": "js-frameworks",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "javascript-to-js-frameworks",
        "source_node_id": "javascript",
        "target_node_id": "js-frameworks",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "js-frameworks-to-react",
        "source_node_id": "js-frameworks",
        "target_node_id": "react",
        "edge_type": "dashed",
        "source_handle": "right",
        "target_handle": "left",
    },
    {
        "handle": "js-frameworks-to-vue",
        "source_node_id": "js-frameworks",
        "target_node_id": "vue",
        "edge_type": "dashed",
        "source_handle": "right",
        "target_handle": "left",
    },
    {
        "handle": "js-frameworks-to-angular",
        "source_node_id": "js-frameworks",
        "target_node_id": "angular",
        "edge_type": "dashed",
        "source_handle": "right",
        "target_handle": "left",
    },
    {
        "handle": "js-frameworks-to-web-performance",
        "source_node_id": "js-frameworks",
        "target_node_id": "web-performance",
        "edge_type": "smoothstep",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "web-performance-to-performance-metrics",
        "source_node_id": "web-performance",
        "target_node_id": "performance-metrics",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
    {
        "handle": "web-performance-to-optimization",
        "source_node_id": "web-performance",
        "target_node_id": "optimization",
        "edge_type": "animated",
        "source_handle": "bottom",
        "target_handle": "top",
    },
]
