/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryResponseDescription } from './categoryResponseDescription';

/**
 * カテゴリのレスポンススキーマ
 */
export interface CategoryResponse {
  id: string;
  code: string;
  title: string;
  description?: CategoryResponseDescription;
  order_index: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
