/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryUpdateRequestCode } from './categoryUpdateRequestCode';
import type { CategoryUpdateRequestTitle } from './categoryUpdateRequestTitle';
import type { CategoryUpdateRequestDescription } from './categoryUpdateRequestDescription';
import type { CategoryUpdateRequestOrderIndex } from './categoryUpdateRequestOrderIndex';
import type { CategoryUpdateRequestIsActive } from './categoryUpdateRequestIsActive';

/**
 * カテゴリの更新リクエストスキーマ
 */
export interface CategoryUpdateRequest {
  code?: CategoryUpdateRequestCode;
  title?: CategoryUpdateRequestTitle;
  description?: CategoryUpdateRequestDescription;
  order_index?: CategoryUpdateRequestOrderIndex;
  is_active?: CategoryUpdateRequestIsActive;
}
