/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryDetailResponseData } from './categoryDetailResponseData';
import type { CategoryDetailResponseError } from './categoryDetailResponseError';

/**
 * カテゴリ詳細のAPIレスポンス
 */
export interface CategoryDetailResponse {
  success: boolean;
  data?: CategoryDetailResponseData;
  error?: CategoryDetailResponseError;
}
