/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreateNewVersionEndpointApiV1RoadmapsRoadmapIdNewVersionPostParams = {
/**
 * 新しいバージョン番号（セマンティックバージョニング形式、例：1.1.0）
 */
new_version: string;
};
