/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentRevisionContentResponseChangeSummary } from './documentRevisionContentResponseChangeSummary';
import type { DocumentRevisionContentResponseCreatedBy } from './documentRevisionContentResponseCreatedBy';
import type { DocumentContentBase } from './documentContentBase';

/**
 * リビジョンコンテンツ付きレスポンス
 */
export interface DocumentRevisionContentResponse {
  version: string;
  change_summary?: DocumentRevisionContentResponseChangeSummary;
  created_at: string;
  id: string;
  document_id: string;
  created_by?: DocumentRevisionContentResponseCreatedBy;
  content: DocumentContentBase;
}
