/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentCreateDescription } from './documentCreateDescription';
import type { DocumentContentBase } from './documentContentBase';

/**
 * ドキュメント作成リクエスト
 */
export interface DocumentCreate {
  title: string;
  description?: DocumentCreateDescription;
  content: DocumentContentBase;
}
