/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentSectionBase } from './documentSectionBase';
import type { DocumentRevisionDiffSectionsModifiedItem } from './documentRevisionDiffSectionsModifiedItem';

/**
 * リビジョン間の差分情報
 */
export interface DocumentRevisionDiff {
  from_version: string;
  to_version: string;
  sections_added?: DocumentSectionBase[];
  sections_removed?: DocumentSectionBase[];
  sections_modified?: DocumentRevisionDiffSectionsModifiedItem[];
}
