/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentSectionBase } from './documentSectionBase';

/**
 * ドキュメントコンテンツの基本構造
 */
export interface DocumentContentBase {
  title: string;
  sections: DocumentSectionBase[];
}
