/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentDetailResponseDescription } from './documentDetailResponseDescription';
import type { DocumentRevisionResponse } from './documentRevisionResponse';

/**
 * 最新リビジョン情報付きドキュメント詳細レスポンス
 */
export interface DocumentDetailResponse {
  title: string;
  description?: DocumentDetailResponseDescription;
  id: string;
  created_at: string;
  updated_at: string;
  latest_revision: DocumentRevisionResponse;
}
