/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentContentBase } from './documentContentBase';
import type { DocumentRevisionCreateChangeSummary } from './documentRevisionCreateChangeSummary';

/**
 * リビジョン作成リクエスト
 */
export interface DocumentRevisionCreate {
  content: DocumentContentBase;
  change_summary?: DocumentRevisionCreateChangeSummary;
  version_type?: string;
}
