/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentWithRevisionsResponseDescription } from './documentWithRevisionsResponseDescription';
import type { DocumentRevisionResponse } from './documentRevisionResponse';

/**
 * リビジョン履歴付きドキュメント情報レスポンス
 */
export interface DocumentWithRevisionsResponse {
  title: string;
  description?: DocumentWithRevisionsResponseDescription;
  id: string;
  created_at: string;
  updated_at: string;
  revisions: DocumentRevisionResponse[];
}
