/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetDocumentDiffApiV1DocumentsDocumentIdDiffGetParams = {
/**
 * 比較元バージョン
 */
from_version: string;
/**
 * 比較先バージョン
 */
to_version: string;
};
