/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetDocumentsApiV1DocumentsGetParams = {
page?: number;
limit?: number;
title_contains?: string | null;
node_id?: string | null;
sort_by?: string;
sort_order?: string;
};
