/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NodeDocumentLinkResponseOrderPosition } from './nodeDocumentLinkResponseOrderPosition';

/**
 * ノードとドキュメントのリンク情報レスポンス
 */
export interface NodeDocumentLinkResponse {
  relation_type?: string;
  order_position?: NodeDocumentLinkResponseOrderPosition;
  id: string;
  node_id: string;
  document_id: string;
  created_at: string;
}
