/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentResponse } from './documentResponse';

/**
 * ノードに関連するドキュメント一覧レスポンス
 */
export interface NodeDocumentsResponse {
  node_id: string;
  node_title: string;
  documents: DocumentResponse[];
}
