/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NodeDocumentLinkCreateOrderPosition } from './nodeDocumentLinkCreateOrderPosition';

/**
 * ノードとドキュメントのリンク作成リクエスト
 */
export interface NodeDocumentLinkCreate {
  relation_type?: string;
  order_position?: NodeDocumentLinkCreateOrderPosition;
  document_id: string;
}
