/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentResponse } from './documentResponse';
import type { PaginationMeta } from './paginationMeta';

/**
 * ページネーション付きドキュメント一覧レスポンス
 */
export interface PaginatedDocumentResponse {
  items: DocumentResponse[];
  meta: PaginationMeta;
}
