/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadRoadmapsApiV1RoadmapsGetParams = {
skip?: number;
limit?: number;
theme_id?: string | null;
is_published?: boolean | null;
is_latest?: boolean | null;
};
