/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapDetailResponseDescription } from './roadmapDetailResponseDescription';
import type { RoadmapDetailResponsePublishedAt } from './roadmapDetailResponsePublishedAt';
import type { ThemeResponse } from './themeResponse';
import type { RoadmapNodeResponse } from './roadmapNodeResponse';
import type { RoadmapEdgeResponse } from './roadmapEdgeResponse';

/**
 * 詳細情報を含むロードマップのレスポンススキーマ
 */
export interface RoadmapDetailResponse {
  id: string;
  theme_id: string;
  version: string;
  title: string;
  description?: RoadmapDetailResponseDescription;
  is_published: boolean;
  is_latest: boolean;
  published_at?: RoadmapDetailResponsePublishedAt;
  created_at: string;
  updated_at: string;
  theme: ThemeResponse;
  nodes: RoadmapNodeResponse[];
  edges: RoadmapEdgeResponse[];
}
