/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeCreateRequestLabel } from './roadmapEdgeCreateRequestLabel';
import type { RoadmapEdgeCreateRequestMetadata } from './roadmapEdgeCreateRequestMetadata';

/**
 * ロードマップエッジの作成リクエストスキーマ
 */
export interface RoadmapEdgeCreateRequest {
  handle: string;
  source_node_id: string;
  target_node_id: string;
  edge_type?: string;
  label?: RoadmapEdgeCreateRequestLabel;
  metadata?: RoadmapEdgeCreateRequestMetadata;
  roadmap_id: string;
}
