/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapCreateRequestDescription } from './roadmapCreateRequestDescription';
import type { RoadmapNodeRequest } from './roadmapNodeRequest';
import type { RoadmapEdgeRequest } from './roadmapEdgeRequest';

/**
 * ロードマップの作成リクエストスキーマ
 */
export interface RoadmapCreateRequest {
  theme_id: string;
  version: string;
  title: string;
  description?: RoadmapCreateRequestDescription;
  is_published?: boolean;
  nodes: RoadmapNodeRequest[];
  edges: RoadmapEdgeRequest[];
}
