/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeLabel } from './roadmapEdgeLabel';
import type { RoadmapEdgeMetadata } from './roadmapEdgeMetadata';

export interface RoadmapEdge {
  handle: string;
  source_node_id: string;
  target_node_id: string;
  edge_type?: string;
  label?: RoadmapEdgeLabel;
  metadata?: RoadmapEdgeMetadata;
  id: string;
  roadmap_id: string;
  created_at: string;
  updated_at: string;
}
