/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeResponseSourceHandle } from './roadmapEdgeResponseSourceHandle';
import type { RoadmapEdgeResponseTargetHandle } from './roadmapEdgeResponseTargetHandle';
import type { RoadmapEdgeResponseLabel } from './roadmapEdgeResponseLabel';
import type { RoadmapEdgeResponseMetadata } from './roadmapEdgeResponseMetadata';

/**
 * ロードマップエッジのレスポンススキーマ
 */
export interface RoadmapEdgeResponse {
  id: string;
  roadmap_id: string;
  handle: string;
  source_node_id: string;
  target_node_id: string;
  source_handle?: RoadmapEdgeResponseSourceHandle;
  target_handle?: RoadmapEdgeResponseTargetHandle;
  edge_type: string;
  label?: RoadmapEdgeResponseLabel;
  metadata?: RoadmapEdgeResponseMetadata;
  created_at: string;
  updated_at: string;
}
