/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeRequestLabel } from './roadmapEdgeRequestLabel';
import type { RoadmapEdgeRequestMetadata } from './roadmapEdgeRequestMetadata';

/**
 * ロードマップエッジのリクエストスキーマ（基本）
 */
export interface RoadmapEdgeRequest {
  handle: string;
  source_node_id: string;
  target_node_id: string;
  edge_type?: string;
  label?: RoadmapEdgeRequestLabel;
  metadata?: RoadmapEdgeRequestMetadata;
}
