/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeUpdateRequestHandle } from './roadmapEdgeUpdateRequestHandle';
import type { RoadmapEdgeUpdateRequestSourceNodeId } from './roadmapEdgeUpdateRequestSourceNodeId';
import type { RoadmapEdgeUpdateRequestTargetNodeId } from './roadmapEdgeUpdateRequestTargetNodeId';
import type { RoadmapEdgeUpdateRequestEdgeType } from './roadmapEdgeUpdateRequestEdgeType';
import type { RoadmapEdgeUpdateRequestLabel } from './roadmapEdgeUpdateRequestLabel';
import type { RoadmapEdgeUpdateRequestMetadata } from './roadmapEdgeUpdateRequestMetadata';

/**
 * ロードマップエッジの更新リクエストスキーマ
 */
export interface RoadmapEdgeUpdateRequest {
  handle?: RoadmapEdgeUpdateRequestHandle;
  source_node_id?: RoadmapEdgeUpdateRequestSourceNodeId;
  target_node_id?: RoadmapEdgeUpdateRequestTargetNodeId;
  edge_type?: RoadmapEdgeUpdateRequestEdgeType;
  label?: RoadmapEdgeUpdateRequestLabel;
  metadata?: RoadmapEdgeUpdateRequestMetadata;
}
