/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeResponseDescription } from './roadmapNodeResponseDescription';
import type { RoadmapNodeResponseMetadata } from './roadmapNodeResponseMetadata';

/**
 * ロードマップノードのレスポンススキーマ
 */
export interface RoadmapNodeResponse {
  id: string;
  roadmap_id: string;
  handle: string;
  node_type: string;
  title: string;
  description?: RoadmapNodeResponseDescription;
  position_x: number;
  position_y: number;
  metadata?: RoadmapNodeResponseMetadata;
  is_required: boolean;
  created_at: string;
  updated_at: string;
}
