/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeDescription } from './roadmapNodeDescription';
import type { RoadmapNodeMetadata } from './roadmapNodeMetadata';

export interface RoadmapNode {
  handle: string;
  node_type: string;
  title: string;
  description?: RoadmapNodeDescription;
  position_x?: number;
  position_y?: number;
  metadata?: RoadmapNodeMetadata;
  is_required?: boolean;
  id: string;
  roadmap_id: string;
  created_at: string;
  updated_at: string;
}
