/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapUpdateRequestThemeId } from './roadmapUpdateRequestThemeId';
import type { RoadmapUpdateRequestVersion } from './roadmapUpdateRequestVersion';
import type { RoadmapUpdateRequestTitle } from './roadmapUpdateRequestTitle';
import type { RoadmapUpdateRequestDescription } from './roadmapUpdateRequestDescription';
import type { RoadmapUpdateRequestIsPublished } from './roadmapUpdateRequestIsPublished';

/**
 * ロードマップの更新リクエストスキーマ
 */
export interface RoadmapUpdateRequest {
  theme_id?: RoadmapUpdateRequestThemeId;
  version?: RoadmapUpdateRequestVersion;
  title?: RoadmapUpdateRequestTitle;
  description?: RoadmapUpdateRequestDescription;
  is_published?: RoadmapUpdateRequestIsPublished;
}
