/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapVersionListResponseData } from './roadmapVersionListResponseData';
import type { RoadmapVersionListResponseError } from './roadmapVersionListResponseError';

/**
 * ロードマップバージョン一覧のAPIレスポンス
 */
export interface RoadmapVersionListResponse {
  success: boolean;
  data?: RoadmapVersionListResponseData;
  error?: RoadmapVersionListResponseError;
}
