/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeCreateDescription } from './roadmapNodeCreateDescription';
import type { RoadmapNodeCreateMetadata } from './roadmapNodeCreateMetadata';

export interface RoadmapNodeCreate {
  handle: string;
  node_type: string;
  title: string;
  description?: RoadmapNodeCreateDescription;
  position_x?: number;
  position_y?: number;
  metadata?: RoadmapNodeCreateMetadata;
  is_required?: boolean;
  roadmap_id: string;
}
