/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeCreateRequestDescription } from './roadmapNodeCreateRequestDescription';
import type { RoadmapNodeCreateRequestMetadata } from './roadmapNodeCreateRequestMetadata';

/**
 * ロードマップノードの作成リクエストスキーマ
 */
export interface RoadmapNodeCreateRequest {
  handle: string;
  node_type: string;
  title: string;
  description?: RoadmapNodeCreateRequestDescription;
  position_x?: number;
  position_y?: number;
  metadata?: RoadmapNodeCreateRequestMetadata;
  is_required?: boolean;
  roadmap_id: string;
}
