/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeRequestDescription } from './roadmapNodeRequestDescription';
import type { RoadmapNodeRequestMetadata } from './roadmapNodeRequestMetadata';

/**
 * ロードマップノードのリクエストスキーマ（作成用）
 */
export interface RoadmapNodeRequest {
  handle: string;
  node_type: string;
  title: string;
  description?: RoadmapNodeRequestDescription;
  position_x?: number;
  position_y?: number;
  metadata?: RoadmapNodeRequestMetadata;
  is_required?: boolean;
}
