/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeCreateLabel } from './roadmapEdgeCreateLabel';
import type { RoadmapEdgeCreateMetadata } from './roadmapEdgeCreateMetadata';

export interface RoadmapEdgeCreate {
  handle: string;
  source_node_id: string;
  target_node_id: string;
  edge_type?: string;
  label?: RoadmapEdgeCreateLabel;
  metadata?: RoadmapEdgeCreateMetadata;
  roadmap_id: string;
}
