/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeUpdateHandle } from './roadmapNodeUpdateHandle';
import type { RoadmapNodeUpdateNodeType } from './roadmapNodeUpdateNodeType';
import type { RoadmapNodeUpdateTitle } from './roadmapNodeUpdateTitle';
import type { RoadmapNodeUpdateDescription } from './roadmapNodeUpdateDescription';
import type { RoadmapNodeUpdatePositionX } from './roadmapNodeUpdatePositionX';
import type { RoadmapNodeUpdatePositionY } from './roadmapNodeUpdatePositionY';
import type { RoadmapNodeUpdateMetadata } from './roadmapNodeUpdateMetadata';
import type { RoadmapNodeUpdateIsRequired } from './roadmapNodeUpdateIsRequired';

export interface RoadmapNodeUpdate {
  handle?: RoadmapNodeUpdateHandle;
  node_type?: RoadmapNodeUpdateNodeType;
  title?: RoadmapNodeUpdateTitle;
  description?: RoadmapNodeUpdateDescription;
  position_x?: RoadmapNodeUpdatePositionX;
  position_y?: RoadmapNodeUpdatePositionY;
  metadata?: RoadmapNodeUpdateMetadata;
  is_required?: RoadmapNodeUpdateIsRequired;
}
