/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapNodeUpdateRequestHandle } from './roadmapNodeUpdateRequestHandle';
import type { RoadmapNodeUpdateRequestNodeType } from './roadmapNodeUpdateRequestNodeType';
import type { RoadmapNodeUpdateRequestTitle } from './roadmapNodeUpdateRequestTitle';
import type { RoadmapNodeUpdateRequestDescription } from './roadmapNodeUpdateRequestDescription';
import type { RoadmapNodeUpdateRequestPositionX } from './roadmapNodeUpdateRequestPositionX';
import type { RoadmapNodeUpdateRequestPositionY } from './roadmapNodeUpdateRequestPositionY';
import type { RoadmapNodeUpdateRequestMetadata } from './roadmapNodeUpdateRequestMetadata';
import type { RoadmapNodeUpdateRequestIsRequired } from './roadmapNodeUpdateRequestIsRequired';

/**
 * ロードマップノードの更新リクエストスキーマ
 */
export interface RoadmapNodeUpdateRequest {
  handle?: RoadmapNodeUpdateRequestHandle;
  node_type?: RoadmapNodeUpdateRequestNodeType;
  title?: RoadmapNodeUpdateRequestTitle;
  description?: RoadmapNodeUpdateRequestDescription;
  position_x?: RoadmapNodeUpdateRequestPositionX;
  position_y?: RoadmapNodeUpdateRequestPositionY;
  metadata?: RoadmapNodeUpdateRequestMetadata;
  is_required?: RoadmapNodeUpdateRequestIsRequired;
}
