/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapResponseDescription } from './roadmapResponseDescription';
import type { RoadmapResponsePublishedAt } from './roadmapResponsePublishedAt';

/**
 * ロードマップのレスポンススキーマ
 */
export interface RoadmapResponse {
  id: string;
  theme_id: string;
  version: string;
  title: string;
  description?: RoadmapResponseDescription;
  is_published: boolean;
  is_latest: boolean;
  published_at?: RoadmapResponsePublishedAt;
  created_at: string;
  updated_at: string;
}
