/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoadmapEdgeUpdateHandle } from './roadmapEdgeUpdateHandle';
import type { RoadmapEdgeUpdateSourceNodeId } from './roadmapEdgeUpdateSourceNodeId';
import type { RoadmapEdgeUpdateTargetNodeId } from './roadmapEdgeUpdateTargetNodeId';
import type { RoadmapEdgeUpdateEdgeType } from './roadmapEdgeUpdateEdgeType';
import type { RoadmapEdgeUpdateLabel } from './roadmapEdgeUpdateLabel';
import type { RoadmapEdgeUpdateMetadata } from './roadmapEdgeUpdateMetadata';

export interface RoadmapEdgeUpdate {
  handle?: RoadmapEdgeUpdateHandle;
  source_node_id?: RoadmapEdgeUpdateSourceNodeId;
  target_node_id?: RoadmapEdgeUpdateTargetNodeId;
  edge_type?: RoadmapEdgeUpdateEdgeType;
  label?: RoadmapEdgeUpdateLabel;
  metadata?: RoadmapEdgeUpdateMetadata;
}
