/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ThemeCreateRequestDescription } from './themeCreateRequestDescription';

/**
 * テーマの作成リクエストスキーマ
 */
export interface ThemeCreateRequest {
  category_id: string;
  code: string;
  title: string;
  description?: ThemeCreateRequestDescription;
  order_index: number;
  is_active?: boolean;
}
