/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ThemeDetailResponseData } from './themeDetailResponseData';
import type { ThemeDetailResponseError } from './themeDetailResponseError';

/**
 * テーマ詳細のAPIレスポンス
 */
export interface ThemeDetailResponse {
  success: boolean;
  data?: ThemeDetailResponseData;
  error?: ThemeDetailResponseError;
}
