/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * MapStack API
 * AI学習プラットフォーム MapStack のバックエンドAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ThemeUpdateRequestCategoryId } from './themeUpdateRequestCategoryId';
import type { ThemeUpdateRequestCode } from './themeUpdateRequestCode';
import type { ThemeUpdateRequestTitle } from './themeUpdateRequestTitle';
import type { ThemeUpdateRequestDescription } from './themeUpdateRequestDescription';
import type { ThemeUpdateRequestOrderIndex } from './themeUpdateRequestOrderIndex';
import type { ThemeUpdateRequestIsActive } from './themeUpdateRequestIsActive';

/**
 * テーマの更新リクエストスキーマ
 */
export interface ThemeUpdateRequest {
  category_id?: ThemeUpdateRequestCategoryId;
  code?: ThemeUpdateRequestCode;
  title?: ThemeUpdateRequestTitle;
  description?: ThemeUpdateRequestDescription;
  order_index?: ThemeUpdateRequestOrderIndex;
  is_active?: ThemeUpdateRequestIsActive;
}
